import { useState, useMemo } from "react";
import { Sparkles, Loader2 } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import type { AIReport } from "@/types/claro";
import { SUPABASE_URL, SUPABASE_KEY } from "@/lib/constants";

interface Props {
  report: AIReport | null | undefined;
  isLoading: boolean;
  orgContract: string;
}

type GenState = "idle" | "loading" | "success" | "error";

/** Lightweight markdown-to-HTML for Gemini output (bold, italic, headings, links, lists, paragraphs) */
function renderMarkdown(text: string): string {
  return text
    // Headings
    .replace(/^### (.+)$/gm, '<h4 class="font-semibold text-gray-900 mt-3 mb-1 text-sm">$1</h4>')
    .replace(/^## (.+)$/gm, '<h3 class="font-semibold text-gray-900 mt-4 mb-1 text-sm">$1</h3>')
    .replace(/^# (.+)$/gm, '<h3 class="font-bold text-gray-900 mt-4 mb-2 text-base">$1</h3>')
    // Bold + italic
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer" class="text-[#1A56DB] hover:underline break-all">$1</a>')
    // Bare URLs
    .replace(/(^|[^"'])(https?:\/\/[^\s<]+)/g, '$1<a href="$2" target="_blank" rel="noopener noreferrer" class="text-[#1A56DB] hover:underline break-all">$2</a>')
    // Unordered list items
    .replace(/^[-*] (.+)$/gm, '<li class="ml-4 list-disc">$1</li>')
    // Paragraphs (double newline)
    .replace(/\n\n+/g, '</p><p class="mt-2">')
    // Single newlines within paragraphs
    .replace(/\n/g, '<br/>');
}

export default function AIReportSection({ report, isLoading, orgContract }: Props) {
  const [genState, setGenState] = useState<GenState>("idle");
  const [expanded, setExpanded] = useState(false);
  const queryClient = useQueryClient();

  const reportHtml = useMemo(() => {
    if (!report?.report_text) return "";
    return renderMarkdown(report.report_text);
  }, [report?.report_text]);

  const generate = async () => {
    setGenState("loading");
    try {
      const res = await fetch(`${SUPABASE_URL}/functions/v1/generate-report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${SUPABASE_KEY}`,
        },
        body: JSON.stringify({ org_contract: orgContract }),
      });
      if (!res.ok) throw new Error("Failed");
      setGenState("success");
      queryClient.invalidateQueries({ queryKey: ["org-report", orgContract] });
      setTimeout(() => setGenState("idle"), 3000);
    } catch {
      setGenState("error");
      setTimeout(() => setGenState("idle"), 3000);
    }
  };

  return (
    <div className="bg-white border border-gray-200 rounded-xl p-4 sm:p-6 shadow-sm overflow-hidden">
      <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="text-[#E3A008] shrink-0" style={{ width: 20, height: 20 }} />
          <span className="text-sm font-semibold text-gray-900">AI Transparency Report</span>
        </div>
        {report && (
          <span className="text-xs text-gray-400">
            Generated {new Date(report.generated_at).toLocaleDateString()}
          </span>
        )}
      </div>

      {isLoading ? (
        <div className="h-24 bg-gray-100 rounded animate-pulse" />
      ) : !report ? (
        <div className="bg-gray-50 rounded-lg p-4 text-center">
          <p className="text-sm text-gray-600">No report generated yet</p>
          <p className="text-xs text-gray-400 mt-1">Generate an AI transparency report powered by Gemini 2.0 Flash.</p>
        </div>
      ) : (
        <div className="min-w-0">
          <div
            className={`text-sm text-gray-700 leading-relaxed break-words overflow-wrap-anywhere ${expanded ? "" : "line-clamp-6"}`}
            dangerouslySetInnerHTML={{ __html: reportHtml }}
          />
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-xs text-[#1A56DB] mt-2 hover:underline"
          >
            {expanded ? "Show less" : "Read full report"}
          </button>
          <p className="text-xs text-gray-400 mt-3">Generated by {report.model_used}</p>
        </div>
      )}

      {/* Generate button */}
      <button
        onClick={generate}
        disabled={genState === "loading"}
        className="mt-4 bg-[#0A0E1A] text-white rounded-md px-4 py-2 text-sm font-medium w-full flex items-center justify-center gap-2 hover:bg-[#0A0E1A]/90 disabled:opacity-50 active:scale-[0.97] transition-all"
      >
        {genState === "loading" ? (
          <><Loader2 className="animate-spin" style={{ width: 16, height: 16 }} /> Generating...</>
        ) : genState === "success" ? (
          "Report generated!"
        ) : (
          <><Sparkles style={{ width: 16, height: 16 }} /> Generate New Report</>
        )}
      </button>
      {genState === "error" && (
        <p className="text-xs text-red-600 mt-2 text-center">Generation failed. Try again.</p>
      )}
    </div>
  );
}
