import { useState } from "react";
import { Sparkles, Loader2 } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import type { AIReport } from "@/types/claro";
import { SUPABASE_URL, SUPABASE_KEY } from "@/lib/constants";

interface Props {
  report: AIReport | null | undefined;
  isLoading: boolean;
  orgContract: string;
}

type GenState = "idle" | "loading" | "success" | "error";

export default function AIReportSection({ report, isLoading, orgContract }: Props) {
  const [genState, setGenState] = useState<GenState>("idle");
  const [expanded, setExpanded] = useState(false);
  const queryClient = useQueryClient();

  const generate = async () => {
    setGenState("loading");
    try {
      const res = await fetch(`${SUPABASE_URL}/functions/v1/generate-report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${SUPABASE_KEY}`,
        },
        body: JSON.stringify({ org_contract: orgContract }),
      });
      if (!res.ok) throw new Error("Failed");
      setGenState("success");
      queryClient.invalidateQueries({ queryKey: ["org-report", orgContract] });
      setTimeout(() => setGenState("idle"), 3000);
    } catch {
      setGenState("error");
      setTimeout(() => setGenState("idle"), 3000);
    }
  };

  return (
    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="text-[#E3A008]" style={{ width: 20, height: 20 }} />
          <span className="text-sm font-semibold text-gray-900">AI Transparency Report</span>
        </div>
        {report && (
          <span className="text-xs text-gray-400">
            Generated {new Date(report.generated_at).toLocaleDateString()}
          </span>
        )}
      </div>

      {isLoading ? (
        <div className="h-24 bg-gray-100 rounded animate-pulse" />
      ) : !report ? (
        <div className="bg-gray-50 rounded-lg p-4 text-center">
          <p className="text-sm text-gray-600">No report generated yet</p>
          <p className="text-xs text-gray-400 mt-1">Generate an AI transparency report powered by Gemini 2.0 Flash.</p>
        </div>
      ) : (
        <div>
          <p className={`text-sm text-gray-700 leading-relaxed whitespace-pre-wrap ${expanded ? "" : "line-clamp-6"}`}>
            {report.report_text}
          </p>
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-xs text-[#1A56DB] mt-2 hover:underline"
          >
            {expanded ? "Show less" : "Read full report"}
          </button>
          <p className="text-xs text-gray-400 mt-3">Generated by {report.model_used}</p>
        </div>
      )}

      {/* Generate button */}
      <button
        onClick={generate}
        disabled={genState === "loading"}
        className="mt-4 bg-[#0A0E1A] text-white rounded-md px-4 py-2 text-sm font-medium w-full flex items-center justify-center gap-2 hover:bg-[#0A0E1A]/90 disabled:opacity-50 active:scale-[0.97] transition-all"
      >
        {genState === "loading" ? (
          <><Loader2 className="animate-spin" style={{ width: 16, height: 16 }} /> Generating...</>
        ) : genState === "success" ? (
          "Report generated!"
        ) : (
          <><Sparkles style={{ width: 16, height: 16 }} /> Generate New Report</>
        )}
      </button>
      {genState === "error" && (
        <p className="text-xs text-red-600 mt-2 text-center">Generation failed. Try again.</p>
      )}
    </div>
  );
}
